const data = [
  {
    title: "Reminders",
    description: "A practical note-taking app inspired by Google Keep that helps you keep your tasks and appointments organized.",
    technologies: ["React", "Node.js", "MongoDB", "Axios"],
    gitLink: "https://github.com/GeisielMelo/reminders",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: null,
    featured: true,
  },
  {
    title: "Reminders API",
    description: "Reminders API is a backend server designed specifically for the Reminders application. It handles the storage and retrieval of data, utilizing the MongoDB database hosted on Atlas.  It seamlessly integrates with the frontend application, enabling users to create, update, and retrieve their data effortlessly.",
    technologies: ["React", "Node.js", "MongoDB", "Express"],
    gitLink: "https://github.com/GeisielMelo/reminders-api",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: null,
    featured: true,
  },
  {
    title: "E-mail Marketing",
    description: "This is a application that receives user data and saves it directly to a Mailchimp database, aiming to simplify and streamline the process of creating and sending email marketing campaigns. ",
    technologies: ["Bootstrap", "Express", "Node", "CSS"],
    gitLink: "https://github.com/GeisielMelo/Email-Marketing",
    imageLink: "https://github.com/GeisielMelo/Email-Marketing/raw/main/README/imgHome.png",
    liveLink: null,
    featured: true,
  },
  {
    title: "Portfolio",
    description: "My portfolio is a platform designed to facilitate communication and showcase my projects. Inspired by Brittany Chiang's design, it was completely written and developed by me. It aims to provide a clear and engaging overview of my work, skills, and experiences.",
    technologies: ["React", "Node.js", "CSS", "Express"],
    gitLink: "https://github.com/GeisielMelo/Portfolio",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: null,
    featured: true,
  },
  {
    title: "LandingPage",
    description: "This project consists of a Landing Page created using only HTML and CSS, with 6 sections, an animated menu, and fully responsive design.",
    technologies: ["JavaScript", "CSS", "HTML"],
    gitLink: "https://github.com/GeisielMelo/LandingPage",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: "https://landingpagegeisielmelo.netlify.app",
    featured: false,
  },
  {
    title: "TinDog",
    description: "In this project, the goal is to create a landing page using the Bootstrap framework that will showcase the mobile app 'TinDog, a 'Tinder' designed specifically for dogs.",
    technologies: ["JavaScript", "CSS", "HTML", "Bootstrap"],  
    gitLink: "https://github.com/GeisielMelo/Tinder-for-Dogs",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: "https://htmlpreview.github.io/?https://github.com/GeisielMelo/Tinder-for-Dogs/blob/main/index.html",
    featured: false,
  },
  {
    title: "E-commerce",
    description: "This project is an e-commerce website built using Django, HTML, CSS, JavaScript, and Python. The website allows users to browse products, add them to their cart, and complete a checkout process. The project also includes an admin panel for managing products, orders, and users.",
    technologies: ["Python", "Django", "HTML", "CSS"],
    gitLink: "https://github.com/GeisielMelo/E-commerce",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: null,
    featured: false,
  },
  {
    title: "Simon-Game",
    description: "Every time you successfully reproduce the sequence, the game will become more challenging, adding more elements to the sequence. But be careful, if you make a mistake, the game will end and you will have to start over.",
    technologies: ["JavaScript", "CSS", "HTML"],
    gitLink: "https://github.com/GeisielMelo/Simon-Game",
    imageLink: "https://github.com/GeisielMelo/Simon-Game/raw/main/readme.png",
    liveLink: "https://htmlpreview.github.io/?https://github.com/GeisielMelo/Simon-Game/blob/main/index.html",
    featured: false,
  },
  {
    title: "Drum",
    description: "Drum is a simple virtual drum app built using HTML, CSS, and JavaScript. With seven different pieces to choose from, including bass drum, snare drum, hi-hat, tom, cymbal, floor tom, and cowbell, you can play the drums using your keyboard or mouse.",
    technologies: ["JavaScript", "CSS", "HTML"],
    gitLink: "https://github.com/GeisielMelo/Drum",
    imageLink: "https://github.com/GeisielMelo/Drum/raw/main/readme.png",
    liveLink: "https://htmlpreview.github.io/?https://github.com/GeisielMelo/Drum/blob/main/index.html",
    featured: false,
  },
  {
    title: "Calculator",
    description: "Designed to handle complex mathematical functions with ease, making it the perfect tool for students.",
    technologies: ["JavaScript", "CSS", "HTML"],
    gitLink: "https://github.com/GeisielMelo/Calculator",
    imageLink: "https://github.com/GeisielMelo/Calculator/raw/main/imgCalculator.png",
    liveLink: "https://htmlpreview.github.io/?https://github.com/GeisielMelo/Calculator/blob/main/index.html",
    featured: false,
  },
  {
    title: "SplashScreen",
    description: "This Circular Splash Screen is designed to check the existence of certain files and create them if they don't exist to ensure proper system functionality. During the verification process, a circular animation will spin on the screen to indicate that the system is being checked and to keep users informed of the verification progress.",
    technologies: ["Python", "PySide6", "SQLite", "CSS"],
    gitLink: "https://github.com/GeisielMelo/SplashScreen",
    imageLink: "https://raw.githubusercontent.com/GeisielMelo/SplashScreen/main/Screenshot.png",
    liveLink: null,
    featured: false,
  },
  { 
    title: "EasySchedule",
    description: "EasySchedule is a user-friendly scheduling application designed to simplify the process of managing appointments and tasks. With a clean and intuitive interface, it allows users to easily create, organize, and track their schedules. ",
    technologies: ["Python", "PySide6", "MySQL", "CSS"],
    gitLink: "https://github.com/GeisielMelo/EasySchedule",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: null,
    featured: false,
  },
];

export default data;
