const data = [
  {
    title: "Reminders",
    description: "",
    technologies: ["React", "Node.js", "MongoDB", "Axios"],
    gitLink: "https://github.com/GeisielMelo/reminders",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: null,
    featured: true,
  },
  {
    title: "Reminders API",
    description: "",
    technologies: ["React", "Node.js", "MongoDB", "Express"],
    gitLink: "https://github.com/GeisielMelo/reminders-api",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: null,
    featured: true,
  },
  {
    title: "E-mail Marketing",
    description: "This is a application that receives user data and saves it directly to a Mailchimp database, aiming to simplify and streamline the process of creating and sending email marketing campaigns. ",
    technologies: ["Bootstrap", "Express", "Node", "CSS"],
    gitLink: "https://github.com/GeisielMelo/Email-Marketing",
    imageLink: "https://github.com/GeisielMelo/Email-Marketing/raw/main/README/imgHome.png",
    liveLink: null,
    featured: true,
  },
  {
    title: "Portfolio",
    description: "",
    technologies: ["React", "Node.js", "CSS", "Express"],
    gitLink: "https://github.com/GeisielMelo/Portfolio",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: null,
    featured: true,
  },
  {
    title: "LandingPage",
    description: "",
    technologies: ["JavaScript", "CSS", "HTML"],
    gitLink: "https://github.com/GeisielMelo/LandingPage",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: "https://landingpagegeisielmelo.netlify.app",
    featured: false,
  },
  {
    title: "TinDog",
    description: "",
    technologies: ["JavaScript", "CSS", "HTML", "Bootstrap"],  
    gitLink: "https://github.com/GeisielMelo/Tinder-for-Dogs",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: "https://htmlpreview.github.io/?https://github.com/GeisielMelo/Tinder-for-Dogs/blob/main/index.html",
    featured: false,
  },
  {
    title: "E-commerce",
    description: "",
    technologies: ["Python", "Django", "HTML", "CSS"],
    gitLink: "https://github.com/GeisielMelo/E-commerce",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: null,
    featured: false,
  },
  {
    title: "Simon-Game",
    description: "",
    technologies: ["JavaScript", "CSS", "HTML"],
    gitLink: "https://github.com/GeisielMelo/Simon-Game",
    imageLink: "https://github.com/GeisielMelo/Simon-Game/raw/main/readme.png",
    liveLink: "https://htmlpreview.github.io/?https://github.com/GeisielMelo/Simon-Game/blob/main/index.html",
    featured: false,
  },
  {
    title: "Drum",
    description: "",
    technologies: ["JavaScript", "CSS", "HTML"],
    gitLink: "https://github.com/GeisielMelo/Drum",
    imageLink: "https://github.com/GeisielMelo/Drum/raw/main/readme.png",
    liveLink: "https://htmlpreview.github.io/?https://github.com/GeisielMelo/Drum/blob/main/index.html",
    featured: false,
  },
  {
    title: "Calculator",
    description: "",
    technologies: ["JavaScript", "CSS", "HTML"],
    gitLink: "https://github.com/GeisielMelo/Calculator",
    imageLink: "https://github.com/GeisielMelo/Calculator/raw/main/imgCalculator.png",
    liveLink: "https://htmlpreview.github.io/?https://github.com/GeisielMelo/Calculator/blob/main/index.html",
    featured: false,
  },
  {
    title: "DNS_Flush",
    description: "",
    technologies: ["Python", "PySide6", "SQLite", "CSS"],
    gitLink: "https://github.com/GeisielMelo/DNS_Flush",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: null,
    featured: false,
  },
  {
    title: "SplashScreen",
    description: "",
    technologies: ["Python", "PySide6", "SQLite", "CSS"],
    gitLink: "https://github.com/GeisielMelo/SplashScreen",
    imageLink: "https://raw.githubusercontent.com/GeisielMelo/SplashScreen/main/Screenshot.png",
    liveLink: null,
    featured: false,
  },
  { 
    title: "EasySchedule",
    description: "",
    technologies: ["Python", "PySide6", "SQLite", "CSS"],
    gitLink: "https://github.com/GeisielMelo/EasySchedule",
    imageLink: "https://img.freepik.com/free-vector/flat-engineering-construction-illustrated_23-2148892788.jpg",
    liveLink: null,
    featured: false,
  },
];

export default data;
